# Copyright 2026 The Sunshine Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Builds the two front-end binaries:
#
#   sunshine-setup.exe      the dialog, with mini_installer.exe inside it
#   sunshine-uninstall.exe  a launcher that finds Windows' own UninstallString
#                           and runs it, asking nothing of its own
#
# Its own compiler invocation, on purpose. ADR-scale reasoning in
# docs/INSTALLER_UI_REVIEW.md D5: a GN target would put this in Chromium's build
# graph, which means editing an upstream BUILD.gn and rebuilding a browser to
# change a dialog. This links against nothing Chromium produces except the
# engine it embeds as a blob, so it does not belong in that graph.

param(
    [string]$Engine = "",
    [string]$OutputDirectory = ""
)

$ErrorActionPreference = "Stop"

$RepositoryRoot = Split-Path -Parent $PSScriptRoot
$Source = Join-Path $RepositoryRoot "installer"

if (-not $Engine) {
    $workspace = $env:SUNSHINE_CHROMIUM_WORKSPACE
    if (-not $workspace) {
        throw "Pass -Engine, or set SUNSHINE_CHROMIUM_WORKSPACE so the engine can be found."
    }
    $Engine = Join-Path $workspace "src\out\Sunshine\mini_installer.exe"
}
if (-not (Test-Path $Engine)) {
    throw "The engine is not at $Engine. Build Chromium first; this front-end embeds its output."
}
if (-not $OutputDirectory) {
    $OutputDirectory = Join-Path $RepositoryRoot "artifacts\windows-x64"
}
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

# A staging directory, so the resource compiler finds the engine and the assets
# beside the .rc without any of them being committed to the tree.
$Staging = Join-Path ([System.IO.Path]::GetTempPath()) ("sunshine-setup-build-" + [System.Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $Staging | Out-Null
try {
    Copy-Item (Join-Path $Source "*") $Staging -Force
    Copy-Item $Engine (Join-Path $Staging "mini_installer.exe") -Force
    Copy-Item (Join-Path $RepositoryRoot "downstream\assets\chrome\app\theme\chromium\win\chromium.ico") (Join-Path $Staging "sunshine.ico") -Force

    # IU-10. The program compares the resource it carries against this value
    # before running it, so the value is written by the build that embedded it
    # and never by hand.
    $hash = (Get-FileHash -Algorithm SHA256 (Join-Path $Staging "mini_installer.exe")).Hash.ToLowerInvariant()
    @"
// Generated by scripts/build_installer_frontend.ps1. Do not edit, and do not
// commit: the value belongs to one build's engine and to no other.
#ifndef SUNSHINE_INSTALLER_ENGINE_HASH_H_
#define SUNSHINE_INSTALLER_ENGINE_HASH_H_

inline constexpr wchar_t kEngineSha256[] = L"$hash";

#endif  // SUNSHINE_INSTALLER_ENGINE_HASH_H_
"@ | Set-Content (Join-Path $Staging "engine_hash.h") -Encoding utf8

    # cl.exe and rc.exe are not on PATH in a bare shell, and they are not on it
    # during a Chromium build either -- gn and ninja locate the toolchain
    # themselves. Assuming PATH here would have failed this step *after* a
    # twenty-minute compile succeeded, which is the class of waste
    # docs/WINDOWS_CHROMIUM_BUILD.md exists to prevent.
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) { throw "vswhere.exe is not at $vswhere; Visual Studio is required to build the front-end." }
    $vsRoot = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if (-not $vsRoot) { throw "No Visual Studio installation with the C++ toolchain was found." }
    $vcvars = Join-Path $vsRoot "VC\Auxiliary\Build\vcvars64.bat"
    if (-not (Test-Path $vcvars)) { throw "vcvars64.bat is not at $vcvars." }

    # Run vcvars in cmd and import what it set, because the compiler needs INCLUDE,
    # LIB and PATH and there is no other way to learn them.
    & cmd.exe /c "`"$vcvars`" >nul && set" | ForEach-Object {
        if ($_ -match "^([^=]+)=(.*)$") {
            Set-Item -Path ("Env:" + $matches[1]) -Value $matches[2] -ErrorAction SilentlyContinue
        }
    }

    Push-Location $Staging
    try {
        & rc.exe /nologo /fo sunshine_setup.res sunshine_setup.rc
        if ($LASTEXITCODE -ne 0) { throw "rc.exe failed with $LASTEXITCODE" }

        # /W4 because this file had never been compiled: one slot spent on
        # warnings is cheaper than three spent discovering the same defects one
        # at a time. /guard:cf and /Qspectre because it runs elevated.
        #
        # uuid.lib is not optional and its absence is a link error, not a
        # warning: FOLDERID_ProgramFiles and FOLDERID_LocalAppData are
        # *declarations* in KnownFolders.h unless INITKNOWNFOLDERS is defined,
        # and their definitions live in uuid.lib. A Visual C++ project links it
        # from the template's AdditionalDependencies; a bare cl.exe line, which
        # is what this is, does not.
        #
        # /MANIFESTUAC:NO because link.exe otherwise generates a trustInfo
        # block of its own and merges it with ours -- two requestedExecutionLevel
        # elements, which is either a diagnostic or a binary the side-by-side
        # loader refuses to start. IU-7 needs exactly one, and it needs to be
        # the one in sunshine_setup.manifest.
        # /MT, and it is the difference between a setup program and a file
        # that does nothing when double-clicked. Without it cl.exe defaults to
        # /MD, the *dynamic* CRT, and the produced binary needs
        # VCRUNTIME140.dll, VCRUNTIME140_1.dll and MSVCP140.dll on whatever
        # machine runs it. The build machine has them because Visual Studio put
        # them there; a machine that has never had a compiler on it does not,
        # and the loader fails before wWinMain is entered -- so every message
        # box this program would show for a real error never runs, and the user
        # sees nothing at all. That is what happened to build #55's installer.
        #
        # An installer is the one program that cannot ask for a redistributable,
        # because installing the redistributable is the thing it exists to do.
        # Chromium's own mini_installer links statically for the same reason.
        & cl.exe /nologo /std:c++20 /W4 /permissive- /EHsc /O2 /GL /MT /guard:cf /Qspectre `
            /DUNICODE /D_UNICODE `
            /Fe:sunshine-setup.exe sunshine_setup.cpp sunshine_setup.res `
            /link /SUBSYSTEM:WINDOWS /LTCG /GUARD:CF /MANIFESTUAC:NO `
            /MANIFEST:EMBED /MANIFESTINPUT:sunshine_setup.manifest `
            user32.lib gdi32.lib shell32.lib ole32.lib advapi32.lib bcrypt.lib `
            comctl32.lib windowscodecs.lib uuid.lib uxtheme.lib
        if ($LASTEXITCODE -ne 0) { throw "cl.exe failed with $LASTEXITCODE" }

        # The uninstall launcher. Built here rather than in a script of its own
        # because it shares this one's toolchain discovery, its staging
        # directory and its icon, and a second copy of vswhere plumbing is a
        # second thing to keep in step.
        #
        # It embeds no engine and carries no dialog, so it links a fraction of
        # what the setup front-end does. /MT for the same reason and it is the
        # same reason as IU-17: an uninstaller is run on machines that never had
        # a compiler, and a loader failure there shows the user nothing at all.
        & rc.exe /nologo /fo sunshine_uninstall.res sunshine_uninstall.rc
        if ($LASTEXITCODE -ne 0) { throw "rc.exe failed for the uninstall launcher with $LASTEXITCODE" }

        & cl.exe /nologo /std:c++20 /W4 /permissive- /EHsc /O2 /GL /MT /guard:cf /Qspectre `
            /DUNICODE /D_UNICODE `
            /Fe:sunshine-uninstall.exe sunshine_uninstall.cpp sunshine_uninstall.res `
            /link /SUBSYSTEM:WINDOWS /LTCG /GUARD:CF /MANIFESTUAC:NO `
            /MANIFEST:EMBED /MANIFESTINPUT:sunshine_uninstall.manifest `
            user32.lib shell32.lib advapi32.lib
        if ($LASTEXITCODE -ne 0) { throw "cl.exe failed for the uninstall launcher with $LASTEXITCODE" }
    }
    finally {
        Pop-Location
    }

    $produced = Join-Path $Staging "sunshine-setup.exe"
    $destination = Join-Path $OutputDirectory "sunshine-setup.exe"
    Copy-Item $produced $destination -Force
    $megabytes = [math]::Round((Get-Item $destination).Length / 1MB, 1)
    Write-Host "Installer front-end ($megabytes MB): $destination"
    Write-Host "Engine SHA-256: $hash"

    $uninstaller = Join-Path $Staging "sunshine-uninstall.exe"
    if (-not (Test-Path $uninstaller)) { throw "the uninstall launcher was not produced" }
    $uninstallDestination = Join-Path $OutputDirectory "sunshine-uninstall.exe"
    Copy-Item $uninstaller $uninstallDestination -Force
    $uninstallKilobytes = [math]::Round((Get-Item $uninstallDestination).Length / 1KB, 1)
    Write-Host "Uninstall launcher ($uninstallKilobytes KB): $uninstallDestination"
}
finally {
    Remove-Item $Staging -Recurse -Force -ErrorAction SilentlyContinue
}
