#!/usr/bin/env python3
"""Prove the product-strings patch is nothing but the rename.

`downstream/patches/0010-sunshine-product-strings.patch` rewrites 542 lines of
`chrome/app/chromium_strings.grd`. Nobody reads 542 lines of diff, and a patch
that large is where an unrelated change goes to hide -- a reworded sentence, a
dropped placeholder, a message quietly deleted. Reviewing it by eye is not a
control; this is.

The rule the patch must satisfy, exactly:

  * every changed line is a line that said `Chromium`,
  * the new line is that line with `Chromium` replaced by `Sunshine`, and
    nothing else,
  * the counts match, so no line is added or removed on the way through,
  * and none of the exclusions is touched.

The exclusions are the messages where `Chromium` names the upstream project
rather than this product -- the copyright, the company, and ChromiumOS.
Renaming those would not be branding, it would be misattribution, and it is the
one mistake a mechanical rewrite makes most naturally.

Everything here is decided from the patch alone, so it runs offline and does
not need the Chromium checkout. What it cannot decide is whether the resulting
grd still parses; that is grit's answer and it comes at build time.

This guard claims no invariant identifier; no contract declares one for the
shape of a patch.
"""

from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]

PATCH_NAME = "0010-sunshine-product-strings.patch"
TARGET = "chrome/app/chromium_strings.grd"
OLD, NEW = "Chromium", "Sunshine"

# Where `Chromium` names upstream rather than this product. Protected as
# phrases, not as message ids, and that distinction is the whole lesson: the
# first attempt listed five messages whose *names* looked like attribution, and
# this check rejected the result -- `ChromiumOS` and the developer note appear
# in dozens of messages whose names look like nothing in particular.
PROTECTED = (
    "ChromiumOS",            # upstream's operating system, a different product
    "Chromium Authors",      # the copyright and the company name
    "Not used in Chromium",  # a note to developers about upstream
)

# The same three, stated as what a correct rename can never produce. Redundant
# with `rename()` on purpose: if the masking below were ever wrong, this is the
# assertion that still fails.
FORBIDDEN_IN_ADDITIONS = tuple(
    phrase.replace(OLD, NEW) for phrase in PROTECTED
)


def rename(line: str) -> str:
    """The rule, defined once. The patch is generated by this and checked by it.

    Masking is by index rather than by a sentinel word, so a protected phrase
    cannot be re-matched by the substitution that follows it.
    """

    masked = line
    for index, phrase in enumerate(PROTECTED):
        masked = masked.replace(phrase, f"\x00{index}\x00")
    masked = masked.replace(OLD, NEW)
    for index, phrase in enumerate(PROTECTED):
        masked = masked.replace(f"\x00{index}\x00", phrase)
    return masked

HUNK = re.compile(r"^@@ ")


def changed_lines(patch_text: str, target: str) -> tuple[list[str], list[str]]:
    """(removed, added) content lines for one file section of a patch."""

    removed: list[str] = []
    added: list[str] = []
    inside = False
    for line in patch_text.splitlines():
        if line.startswith("+++ b/"):
            inside = line[6:] == target
            continue
        if line.startswith("--- ") or line.startswith("diff --git "):
            continue
        if not inside or HUNK.match(line):
            continue
        if line.startswith("-"):
            removed.append(line[1:])
        elif line.startswith("+"):
            added.append(line[1:])
    return removed, added


def check(root: Path = ROOT) -> list[str]:
    failures: list[str] = []
    patch = root / "downstream/patches" / PATCH_NAME
    if not patch.is_file():
        return [f"{PATCH_NAME} is missing"]

    removed, added = changed_lines(patch.read_text(encoding="utf-8"), TARGET)
    if not removed:
        return [f"{PATCH_NAME} changes nothing in {TARGET}"]

    if len(removed) != len(added):
        failures.append(
            f"{PATCH_NAME} removes {len(removed)} line(s) and adds {len(added)}; "
            "a rename replaces lines one for one, so this patch does something else too"
        )
        return failures

    for index, (before, after) in enumerate(zip(removed, added), start=1):
        if OLD not in before:
            failures.append(
                f"{PATCH_NAME}: changed line {index} did not say {OLD!r}, "
                f"so it is not part of the rename: {before.strip()!r}"
            )
        elif rename(before) != after:
            failures.append(
                f"{PATCH_NAME}: changed line {index} is not the rename. "
                f"expected {rename(before).strip()!r}, got {after.strip()!r}"
            )

    for index, after in enumerate(added, start=1):
        for forbidden in FORBIDDEN_IN_ADDITIONS:
            if forbidden in after:
                failures.append(
                    f"{PATCH_NAME}: added line {index} contains {forbidden!r} -- "
                    "the rename reached a string where Chromium is upstream's name, "
                    "not this product's"
                )
    return failures


def main() -> int:
    failures = check()
    if failures:
        for failure in failures[:20]:
            print(f"Branding substitution check failed: {failure}", file=sys.stderr)
        if len(failures) > 20:
            print(f"... and {len(failures) - 20} more", file=sys.stderr)
        return 1
    removed, _ = changed_lines(
        (ROOT / "downstream/patches" / PATCH_NAME).read_text(encoding="utf-8"), TARGET
    )
    print(
        f"Branding substitution check passed: {PATCH_NAME} changes {len(removed)} "
        f"line(s) of {TARGET}, every one of them {OLD} -> {NEW} and nothing else."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
